name: Build and Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [block-explorer, block-explorer-indexer]

    steps:
      - uses: ./.github/workflows/reusable-build-image.yml
        with:
          project: ${{ matrix.project }}