name: Build Image

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: docker buildx build ${{ inputs.project }}
